routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home.index');
Route::resource('departments', 'DepartmentController')->except(['show']);
Route::resource('employees', 'EmployeeController')->except(['show']);

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $fillable = ['title'];

    public function employees()
    {
        return $this->belongsToMany(Employee::class, 'departments_employees');
    }
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = ['firstname', 'lastname', 'gender', 'salary'];

    const GENDER_MALE = 'male';
    const GENDER_FEMALE = 'female';

    public function departments()
    {
        return $this->belongsToMany(Department::class, 'departments_employees');
    }

    public function getFullnameAttribute()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function isFemale()
    {
        return $this->gender == self::GENDER_FEMALE;
    }

    public function isMale()
    {
        return $this->gender == self::GENDER_MALE;
    }

    public static function listGenders()
    {
        return [
            self::GENDER_MALE => 'Male',
            self::GENDER_FEMALE => 'Female',
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DepartmentFormRequest;
use App\Models\Department;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    public function index()
    {
        $departments = Department::with('employees')->get();

        return view('departments.index', compact('departments'));
    }

    public function create()
    {
        return view('departments.create', [
            'department' => new Department,
        ]);
    }

    public function store(DepartmentFormRequest $request)
    {
        $department = new Department;
        $department->title = $request->title;
        $department->save();

        return response()->redirectToRoute('departments.edit', $department);
    }

    public function edit(Department $department)
    {
        return view('departments.edit', compact('department'));
    }

    public function update(Request $request, Department $department)
    {
        $department->title = $request->title;
        $department->update();

        return response()->redirectToRoute('departments.edit', $department);
    }

    public function destroy(Department $department)
    {
        if ($department->employees->count()) {
            return back()->withError('Department has employees');
        }

        $department->delete();

        return response()->redirectToRoute('departments.index');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeFormRequest;
use App\Models\Department;
use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    public function index()
    {
        $employees = Employee::with('departments')->get();

        return view('employees.index', compact('employees'));
    }

    public function create()
    {
        return view('employees.create', [
            'employee' => new Employee(),
            'departments' => Department::all()
        ]);
    }

    public function store(EmployeeFormRequest $request)
    {
        $employee = new Employee();
        $employee->fill($request->except('departments'));
        $employee->save();
        $employee->departments()->sync($request->departments);

        return response()->redirectToRoute('employees.edit', $employee);
    }

    public function edit(Employee $employee)
    {
        $employee->load('departments');
        $departments = Department::all();

        return view('employees.edit', compact('employee', 'departments'));
    }

    public function update(EmployeeFormRequest $request, Employee $employee)
    {
        $employee->fill($request->all());
        $employee->update();
        $employee->departments()->sync($request->departments);

        return response()->redirectToRoute('employees.edit', $employee);
    }

    public function destroy(Employee $employee)
    {
        $employee->departments()->detach();
        $employee->delete();

        return response()->redirectToRoute('employees.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use App\Models\Employee;

class HomeController extends Controller
{
    public function index()
    {
        $departments = Department::all();
        $employees = Employee::with('departments')->get();

        return view('home', compact('employees', 'departments'));
    }
}

resources/views/departments/_form.blade.php
<div class="form-inner">
    @csrf
    <div class="form-group">
        <label>Title</label>
        <input type="text"
               class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}"
               name="title"
               value="{{ old('title', $department->title) }}">
        {!! $errors->first('title','<small class="invalid-feedback">:message</small>') !!}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</div>

resources/views/departments/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-header clearfix">
            <h1 class="page-title float-left">Departments - New</h1>
        </div>
        <form action="{{ route('departments.store') }}" enctype="multipart/form-data" method="post">
            @include('departments._form')
        </form>
    </div>
@endsection

resources/views/departments/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-header clearfix">
            <h1 class="page-title float-left">Departments - {{ $department->title }} - <small>edit</small></h1>
            <div class="page-actions float-right">
                <form action="{{ route('departments.destroy', $department) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <div class="btn-group">
                        <button type="submit" class="btn btn-danger">delete</button>
                    </div>
                </form>
            </div>
        </div>
        @if (\Session::has('error'))
            <div class="alert alert-danger">
                {!! \Session::get('error') !!}
            </div>
        @endif
        <form action="{{ route('departments.update', $department) }}" enctype="multipart/form-data" method="post">
            {{ method_field('PUT') }}
            @include('departments._form')
        </form>
    </div>
@endsection

resources/views/departments/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-header clearfix">
            <h1 class="page-title float-left">Departments</h1>
            <div class="page-actions float-right">
                <div class="btn-group">
                    <a href="{{ route('departments.create') }}" class="btn btn-primary">create new</a>
                </div>
            </div>
        </div>
        @if ($departments->isNotEmpty())
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Employees</th>
                        <th>Max. salary</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($departments as $department)
                    <tr>
                        <th>1</th>
                        <td>{{ $department->title }}</td>
                        <td>{{ $department->employees->count() }}</td>
                        <td>{{ $department->employees->max('salary') }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('departments.edit', $department) }}" class="btn btn-primary">edit</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-danger" role="alert">
                Empty data!
            </div>
        @endif
    </div>
@endsection

resources/views/employees/_form.blade.php
<div class="form-inner">
    @csrf
    <div class="form-group">
        <label>Firsname:</label>
        <input type="text"
               class="form-control {{ $errors->has('firstname') ? 'is-invalid' : '' }}"
               name="firstname"
               value="{{ old('firstname', $employee->firstname) }}">
        {!! $errors->first('firstname','<small class="invalid-feedback">:message</small>') !!}
    </div>
    <div class="form-group">
        <label>Lastname:</label>
        <input type="text"
               class="form-control {{ $errors->has('lastname') ? 'is-invalid' : '' }}"
               name="lastname"
               value="{{ old('lastname', $employee->lastname) }}">
        {!! $errors->first('lastname','<small class="invalid-feedback">:message</small>') !!}
    </div>
    <div class="form-group">
        <label>Gender:</label>
        <div class="form-check">
            <input type="radio"
                   class="form-check-input {{ $errors->has('gender') ? 'is-invalid' : '' }}"
                   name="gender"
                   id="gender_male"
                   value="male"
                   {{ old('gender', $employee->gender) == 'male' ? 'checked' : '' }}
            >
            <label class="form-check-label" for="gender_male">Male</label>
        </div>
        <div class="form-check">
            <input type="radio"
                   class="form-check-input {{ $errors->has('gender') ? 'is-invalid' : '' }}"
                   name="gender"
                   id="gender_female"
                   value="female"
                    {{ old('gender', $employee->gender) == 'female' ? 'checked' : '' }}
            >
            <label class="form-check-label" for="gender_female">Female</label>
            {!! $errors->first('gender','<small class="invalid-feedback">:message</small>') !!}
        </div>
    </div>
    <div class="form-group">
        <label>Salary:</label>
        <input type="text"
               class="form-control {{ $errors->has('salary') ? 'is-invalid' : '' }}"
               name="salary"
               value="{{ old('salary', $employee->salary) }}">
        {!! $errors->first('salary','<small class="invalid-feedback">:message</small>') !!}
    </div>
    <div class="form-group">
        <label>Departments:</label>
        <select class="custom-select select {{ $errors->has('departments') ? 'is-invalid' : '' }}" name="departments[]" multiple="multiple">
            @foreach($departments as $department)
                <option value="{{ $department->id }}" {{ $employee->departments->contains($department->id) ? 'selected' : '' }}>{{ $department->title }}</option>
            @endforeach
        </select>
        {!! $errors->first('departments','<small class="invalid-feedback">:message</small>') !!}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</div>

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-header clearfix">
            <h1 class="page-title float-left">Employees - New</h1>
        </div>
        <form action="{{ route('employees.store') }}" enctype="multipart/form-data" method="post">
            @include('employees._form')
        </form>
    </div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-header clearfix">
            <h1 class="page-title float-left">Employee - {{ $employee->fullname }} - <small>edit</small></h1>
            <div class="page-actions float-right">
                <form action="{{ route('employees.destroy', $employee) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <div class="btn-group">
                        <button type="submit" class="btn btn-danger">delete</button>
                    </div>
                </form>
            </div>
        </div>
        <form action="{{ route('employees.update', $employee) }}" enctype="multipart/form-data" method="post">
            {{ method_field('PUT') }}
            @include('employees._form')
        </form>
    </div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-header clearfix">
            <h1 class="page-title float-left">Employees</h1>
            <div class="page-actions float-right">
                <div class="btn-group">
                    <a href="{{ route('employees.create') }}" class="btn btn-primary">create new</a>
                </div>
            </div>
        </div>
        @if ($employees->isNotEmpty())
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Fullname</th>
                        <th>Gender</th>
                        <th>Salary</th>
                        <th>Departments</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($employees as $employee)
                    <tr>
                        <th>{{ $loop->iteration }}</th>
                        <td>{{ $employee->fullname }}</td>
                        <td>
                            <span class="badge badge-{{ $employee->isFemale() ? 'primary' : 'secondary' }}">{{ $employee->gender }}</span>
                        </td>
                        <td>{{ $employee->salary }}</td>
                        <td>
                            @if ($employee->departments->isNotEmpty())
                                {{ $employee->departments->implode('title', ', ') }}
                            @endif
                        </td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ route('employees.edit', $employee) }}" class="btn btn-primary">edit</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-danger" role="alert">
                Empty data!
            </div>
        @endif
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-header clearfix">
            <h1 class="page-title float-left">Home</h1>
        </div>
        @if ($employees->isNotEmpty())
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th></th>
                    @foreach($departments as $department)
                        <th class="text-center">{{ $department->title }}</th>
                    @endforeach
                </tr>
                </thead>
                <tbody>
                @foreach($employees as $employee)
                    <tr>
                        <th>{{ $employee->fullname }}</th>
                        @foreach($departments as $department)
                            <td class="text-center">{!! $employee->departments->contains($department->id) ? '<i class="fa fa-check"></i>' : '' !!}</td>
                        @endforeach
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-danger" role="alert">
                Empty data!
            </div>
        @endif
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Demo Project</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/app.css">
    </head>
    <body>
        <div id="app">
            <header class="header">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a class="nav-link {{ request()->routeIs('home.index') ? 'active' : '' }}" href="{{ route('home.index') }}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('*departments*') ? 'active' : '' }}" href="{{ route('departments.index') }}">Departments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {{ request()->is('*employees*') ? 'active' : '' }}" href="{{ route('employees.index') }}">Employees</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <main class="main">
                @yield('content')
            </main>
        </div>

        <!-- SCRIPTS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
        <script src="/js/app.js"></script>
    </body>
</html>